CREATE SCHEMA pnd AUTHORIZATION pnd;

CREATE TABLE pnd_file (
  id int NOT NULL generated by default as identity,
  name varchar(255) NOT NULL,
  parent_id int NOT NULL DEFAULT 0,
  type varchar(45) NOT NULL,
  gmt_modified timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  gmt_create timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  resource_id int DEFAULT NULL,
  constraint pnd_file_id_key PRIMARY KEY (id));

CREATE INDEX index2 ON pnd_file(parent_id, name);

CREATE TABLE pnd_resource (
  id int NOT NULL generated by default as identity,
  size int DEFAULT 0,
  path varchar(255) DEFAULT '',
  uuid varchar(255) DEFAULT '',
  gmt_modified timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  gmt_create timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  status varchar(45) NOT NULL,
  crc varchar(32) NOT NULL,
  link int DEFAULT 0,
  constraint pnd_resource_id_key PRIMARY KEY (id));