CREATE SCHEMA pnd AUTHORIZATION pnd;

CREATE TABLE file (
  id bigint NOT NULL generated by default as identity,
  file_name varchar(100) NOT NULL,
  parent_id bigint NOT NULL DEFAULT 0,
  type varchar(45) NOT NULL,
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  resource_id bigint DEFAULT NULL,
  constraint pnd_file_id_key PRIMARY KEY (id));

CREATE INDEX index2 ON file(parent_id, file_name);

CREATE TABLE resource (
  id bigint NOT NULL generated by default as identity,
  size bigint DEFAULT 0,
  path varchar(100) DEFAULT '',
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  link int DEFAULT 0,
  constraint pnd_resource_id_key PRIMARY KEY (id));

CREATE TABLE resource_chunk (
  id bigint NOT NULL generated by default as identity,
  chunk_number int NOT NULL,
  chunk_size int NOT NULL,
  current_chunk_size int NOT NULL,
  total_size int NOT NULL,
  identifier varchar(100) NOT NULL,
  filename varchar(100) NOT NULL,
  relative_path varchar(100) NOT NULL,
  total_chunks int NOT NULL,
  create_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  update_time timestamp NOT NULL DEFAULT '2019-01-01 00:00:00',
  constraint pnd_resource_chunk_id_key PRIMARY KEY (id));